# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_apartment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='user',
            new_name='owner',
        ),
    ]
