# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0006_auto_20180117_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
